---
title: "4.12codes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
Amybox<- ggplot(Predict320ATNv2, aes(x = Status, y =Amy320last, fill=Status )) +
  geom_boxplot(outlier.size = 0) +
  geom_point(pch = 21, position = position_jitterdodge(), size=3)+labs(y="Observed Amyloid")+ theme_bw() +  
  theme( aspect.ratio=3/4,
         axis.title.x=element_blank(),
           
         axis.text.x = element_text(size=rel(1.13) ),
    text = element_text(size=30),
    # change legend font size
    legend.text=element_text(size=30),
    # Remove panel grid lines
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Remove panel background
  panel.background = element_blank(),
    legend.key=element_blank(),
    legend.background=element_blank(),
    legend.title = element_blank(),
    legend.position ="none",
  legend.direction = "vertical",
    legend.justification = c(0.05, 0.1),
    legend.box.just = "right",
    legend.key.size = unit(1, "cm")
    )   

 Amybox

ggsave(
  file="Amybox.png",
  plot = Amybox,
  device = "png",
 # path = NULL,
  #scale = 1,
  width = 4*1.8,
  height = 3*1.8,
  units = "in"
  #dpi = 300,
  #limitsize = TRUE,
)

 


 
Taubox <- ggplot(Predict320ATNv2, aes(x = Status, y =Tau320last, fill=Status )) +
  geom_boxplot(outlier.size = 0) +
  geom_point(pch = 21, position = position_jitterdodge(), size=3)+labs(y="Observed Tau") +scale_y_continuous(
  labels = scales::number_format(accuracy = 0.05)) + theme_bw() +  
  theme( aspect.ratio=3/4,
         axis.title.x=element_blank(),
    
           
         axis.text.x = element_text(size=rel(1.13) ),
    text = element_text(size=30),
    # change legend font size
    legend.text=element_text(size=30),
    # Remove panel grid lines
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Remove panel background
  panel.background = element_blank(),
    legend.key=element_blank(),
    legend.background=element_blank(),
    legend.title = element_blank(),
    legend.position  ="none",
  legend.direction = "vertical",
    legend.justification = c(0.05, 0.1),
    legend.box.just = "right",
    legend.key.size = unit(1, "cm")
    )  
 Taubox
ggsave(
  file="Taubox.png",
  plot = Taubox,
  device = "png",
 # path = NULL,
  #scale = 1,
  width = 4*1.8,
  height = 3*1.8,
  units = "in"
  #dpi = 300,
  #limitsize = TRUE,
)

 ```