---
title: "newfigureapoe4"
output: html_document
---


# turn back to amy and tau


```{r}
TABLE<-data.frame(table(Amyloid_SUVR$PTID))
TABLE<- TABLE[which(TABLE$Freq>=1),]
 
Amyloid_First<- as.data.frame(matrix(0,nrow(TABLE), ncol(Amyloid_SUVR)))
for (i in 1:nrow(TABLE)){
Amyloid_First[i,] <- as.data.frame(Amyloid_SUVR[max(which(Amyloid_SUVR$PTID == TABLE$Var1[i])), ])

}
colnames(Amyloid_First) <- colnames(Amyloid_SUVR)

```

```{r}

Amyloid_APOE4 <- as.data.frame(Amyloid_First[which(Amyloid_First$APOE4 != 0), ])
Amyloid_UNAPOE4 <- as.data.frame(Amyloid_First[which(Amyloid_First$APOE4 == 0), ])




APOE4<-as.data.frame(rowMeans(Amyloid_APOE4[,c(12:159)]))
UNAPOE4<-as.data.frame(rowMeans(Amyloid_UNAPOE4[,c(12:159)]))

```


```{r}
APOE4$APOE <- c("Carrier")
UNAPOE4$APOE <- c("Non-carrier")

colnames(APOE4)<-c("Value","Carrier")
colnames(UNAPOE4)<-c("Value","Carrier")
APOE4_final <- rbind(APOE4,UNAPOE4)

```
## new amy and tau
```{r}
library(ggsignif)
Amybox<- ggplot(APOE4_final, aes(x = Carrier, y =Value, fill=Carrier )) +
  geom_boxplot(outlier.shape = NA,lwd=1) +
 labs(y="Amyloid")+ theme_bw() + 
  geom_signif(comparisons = list(c("Carrier", "Non-carrier")), 
              map_signif_level=TRUE, y_position = c(2.9, 2.95),lwd=1,textsize=8)+
  ylim(min(APOE4_final$Value),3.1)+
  theme( aspect.ratio=3/4,
         axis.title.x=element_blank(),
           
         axis.text.x = element_text(size=rel(1.13) ),
    text = element_text(size=30),
    # change legend font size
    legend.text=element_text(size=30),
    # Remove panel grid lines
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Remove panel background
  panel.background = element_blank(),
    legend.key=element_blank(),
    legend.background=element_blank(),
    legend.title = element_blank(),
    legend.position ="none",
  legend.direction = "vertical",
    legend.justification = c(0.05, 0.1),
    legend.box.just = "right",
    legend.key.size = unit(1, "cm")
    )   

 Amybox
 
 
 ggsave(
  file="AmyloidAPOE.png",
  plot = Amybox,
  device = "png",
 # path = NULL,
  #scale = 1,
  width = 4*1.8,
  height = 3*1.8,
  units = "in"
  #dpi = 300,
  #limitsize = TRUE,
)
```







```{r}
TABLE<-data.frame(table(Amyloid_SUVR$PTID))
TABLE<- TABLE[which(TABLE$Freq>=1),]
 
Amyloid_First<- as.data.frame(matrix(0,nrow(TABLE), ncol(Amyloid_SUVR)))
for (i in 1:nrow(TABLE)){
Amyloid_First[i,] <- as.data.frame(Amyloid_SUVR[min(which(Amyloid_SUVR$PTID == TABLE$Var1[i])), ])

}
colnames(Amyloid_First) <- colnames(Amyloid_SUVR)

```

```{r}

Amyloid_APOE4 <- as.data.frame(Amyloid_First[which(Amyloid_First$APOE4 == 0), ])
Amyloid_UNAPOE4 <- as.data.frame(Amyloid_First[which(Amyloid_First$APOE4 != 0), ])




APOE4<-as.data.frame(rowMeans(Amyloid_APOE4[,c(12:159)]))
UNAPOE4<-as.data.frame(rowMeans(Amyloid_UNAPOE4[,c(12:159)]))

```


```{r}
APOE4$APOE <- c("Apoe Carrier")
UNAPOE4$APOE <- c("Apoe Non Carrier")

colnames(APOE4)<-c("Value","Carrier")
colnames(UNAPOE4)<-c("Value","Carrier")
APOE4_final <- rbind(APOE4,UNAPOE4)

```
## new amy and tau
```{r}
library(ggsignif)
Amybox<- ggplot(APOE4_final, aes(x = Carrier, y =Value, fill=Carrier )) +
  geom_boxplot(outlier.size = 0) +
  geom_point(pch = 21, position = position_jitterdodge(), size=3)+labs(y="Observed Amyloid")+ theme_bw() + 
  geom_signif(comparisons = list(c("Overestimated", "Underestimated")), 
              map_signif_level=TRUE)+
  #ylim(1.2,max(Pred148_Amy$Amyloid))+
  theme( aspect.ratio=3/4,
         axis.title.x=element_blank(),
           
         axis.text.x = element_text(size=rel(1.13) ),
    text = element_text(size=30),
    # change legend font size
    legend.text=element_text(size=30),
    # Remove panel grid lines
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Remove panel background
  panel.background = element_blank(),
    legend.key=element_blank(),
    legend.background=element_blank(),
    legend.title = element_blank(),
    legend.position ="none",
  legend.direction = "vertical",
    legend.justification = c(0.05, 0.1),
    legend.box.just = "right",
    legend.key.size = unit(1, "cm")
    )   

 Amybox
 
 
 ggsave(
  file="AmyloidAPOE.png",
  plot = Amybox,
  device = "png",
 # path = NULL,
  #scale = 1,
  width = 4*1.8,
  height = 3*1.8,
  units = "in"
  #dpi = 300,
  #limitsize = TRUE,
)
```